version: "2"
services:
  mdocs-front:
    container_name: mdocs-front
    build:
      context: ./mdocs-front
      dockerfile: Dockerfile
    networks:
      mdocs:
        aliases:
          - mdocs-front
    volumes:
      - ./mdocs-front:/usr/src/app
      - /usr/src/app/node_modules
      # - /usr/src/app/.next
    env_file:
      - ./env/mdocs-front.env
    # ports:
    #   - "3000:3000"
  mdocs-api:
    container_name: mdocs-api
    build:
      context: ./mdocs-api
      dockerfile: Dockerfile
    networks:
      mdocs:
        aliases:
          - mdocs-api
    volumes:
      - ./mdocs-api:/usr/src/app
      - /usr/src/app/_build
      - /usr/src/app/deps
    env_file:
      - ./env/mdocs-api.env
    # ports:
    #   - "4000:4000"
    tty: true
    stdin_open: true
  mdocs-nginx:
    container_name: mdocs-nginx
    restart: always
    build: ./nginx
    depends_on:
      - mdocs-api
    networks:
      mdocs:
        aliases:
          - nginx
    # volumes:
    #   - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"
networks:
  mdocs:

